apiVersion: v1
kind: Service
metadata:
  name: chat-api
  labels:
    app: chat-api
    service: chat-api
spec:
  type: NodePort
  selector:
    app: chat-api
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
