apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: awssecretsmanager
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
  - name: region
    value: "us-east-1"
  - name: accessKey
    secretKeyRef:
      name: aws-credentials
      key: accessKey
  - name: secretKey
    secretKeyRef:
      name: aws-credentials
      key: secretKey
auth:
  secretStore: kubernetes
