apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
    service: notification
spec:
  type: ClusterIP
  selector:
    app: notification
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    protocol: TCP
  - name: dapr-http
    port: 3500
    targetPort: 3500
    protocol: TCP
  - name: dapr-grpc
    port: 50001
    targetPort: 50001
    protocol: TCP
