apiVersion: v1
kind: Service
metadata:
  name: websocket-sync
  labels:
    app: websocket-sync
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8004
    protocol: TCP
    name: http
  selector:
    app: websocket-sync
