#!/bin/bash
# Deployment Script for Todo Chatbot
# Generated by: Claude Code (Claude Sonnet 4.5)
# Date: 2026-02-03

set -e

echo "=== Todo Chatbot Deployment Script ==="
echo ""

# Configuration
CHART_PATH="deployment/helm/todo-chatbot"
RELEASE_NAME="todo-chatbot"
NAMESPACE="default"
BACKEND_IMAGE="todo-backend:v1.0.0"
FRONTEND_IMAGE="todo-frontend:v1.0.0"

# Step 1: Verify prerequisites
echo "Step 1: Verifying prerequisites..."
if ! command -v minikube &> /dev/null; then
    echo "ERROR: minikube not found. Please install Minikube."
    exit 1
fi

if ! command -v kubectl &> /dev/null; then
    echo "ERROR: kubectl not found. Please install kubectl."
    exit 1
fi

if ! command -v helm &> /dev/null; then
    echo "ERROR: helm not found. Please install Helm v3."
    exit 1
fi

echo "✓ All prerequisites installed"
echo ""

# Step 2: Check Minikube status
echo "Step 2: Checking Minikube status..."
if ! minikube status &> /dev/null; then
    echo "Minikube not running. Starting Minikube..."
    minikube start --cpus=4 --memory=8192 --disk-size=20g
else
    echo "✓ Minikube is running"
fi
echo ""

# Step 3: Configure Docker environment
echo "Step 3: Configuring Docker environment for Minikube..."
eval $(minikube docker-env)
echo "✓ Docker environment configured"
echo ""

# Step 4: Build container images
echo "Step 4: Building container images..."
echo "Building backend image..."
docker build -t $BACKEND_IMAGE -f deployment/dockerfiles/backend.Dockerfile ./backend
echo "✓ Backend image built"

echo "Building frontend image..."
docker build -t $FRONTEND_IMAGE -f deployment/dockerfiles/frontend.Dockerfile ./frontend
echo "✓ Frontend image built"
echo ""

# Step 5: Verify images
echo "Step 5: Verifying images..."
docker images | grep todo-
echo ""

# Step 6: Validate Helm chart
echo "Step 6: Validating Helm chart..."
helm lint $CHART_PATH
echo "✓ Helm chart validated"
echo ""

# Step 7: Deploy application
echo "Step 7: Deploying application..."
helm install $RELEASE_NAME $CHART_PATH \
  --namespace $NAMESPACE \
  --wait \
  --timeout 5m

echo "✓ Application deployed"
echo ""

# Step 8: Verify deployment
echo "Step 8: Verifying deployment..."
kubectl get pods -l app=todo-chatbot
kubectl get services -l app=todo-chatbot
echo ""

# Step 9: Get frontend URL
echo "Step 9: Getting frontend URL..."
FRONTEND_URL=$(minikube service todo-chatbot-frontend --url)
echo "Frontend URL: $FRONTEND_URL"
echo ""

# Step 10: Log deployment
echo "Step 10: Logging deployment..."
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
cat >> deployment/docs/deployment-log.md <<EOF

## Deployment: $TIMESTAMP

**Version**: v1.0.0
**Action**: Initial deployment
**Tool**: deploy.sh (automated script)
**Status**: Success
**Pods**:
$(kubectl get pods -l app=todo-chatbot -o wide)

**Services**:
$(kubectl get services -l app=todo-chatbot)

**Frontend URL**: $FRONTEND_URL
**Commit**: $(git rev-parse --short HEAD)
**Notes**: First production deployment via automated script

EOF

echo "✓ Deployment logged"
echo ""

echo "=== Deployment Complete ==="
echo "Access the application at: $FRONTEND_URL"
