#!/bin/bash
# Rollback Script for Todo Chatbot
# Generated by: Claude Code (Claude Sonnet 4.5)
# Date: 2026-02-03

set -e

# Configuration
RELEASE_NAME="todo-chatbot"
NAMESPACE="default"

echo "=== Rollback Todo Chatbot Deployment ==="
echo ""

# Get current revision
CURRENT_REVISION=$(helm history $RELEASE_NAME -n $NAMESPACE --max 1 -o json | jq -r '.[0].revision')
echo "Current revision: $CURRENT_REVISION"

# Show revision history
echo ""
echo "Revision history:"
helm history $RELEASE_NAME -n $NAMESPACE

# Parse target revision (optional argument)
if [ $# -eq 1 ]; then
    TARGET_REVISION=$1
    echo ""
    echo "Rolling back to revision: $TARGET_REVISION"
else
    TARGET_REVISION=$((CURRENT_REVISION - 1))
    echo ""
    echo "Rolling back to previous revision: $TARGET_REVISION"
fi

# Confirm rollback
read -p "Proceed with rollback? (yes/no): " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Rollback cancelled"
    exit 0
fi

# Execute rollback
echo ""
echo "Executing rollback..."
if [ $# -eq 1 ]; then
    helm rollback $RELEASE_NAME $TARGET_REVISION --namespace=$NAMESPACE --wait
else
    helm rollback $RELEASE_NAME --namespace=$NAMESPACE --wait
fi

# Verify rollback
echo ""
echo "Verifying rollback..."
kubectl get pods -l app=todo-chatbot
kubectl get services -l app=todo-chatbot

# Log rollback event
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
cat >> deployment/docs/deployment-log.md <<EOF

## Rollback Event: $TIMESTAMP

**Action**: Rollback
**From Revision**: $CURRENT_REVISION
**To Revision**: $TARGET_REVISION
**Status**: Success
**Reason**: Manual rollback via rollback.sh
**Commit**: $(git rev-parse --short HEAD)

EOF

echo ""
echo "=== Rollback Complete ==="
echo "Rolled back from revision $CURRENT_REVISION to $TARGET_REVISION"
