#!/bin/bash
# Scaling Script for Todo Chatbot
# Generated by: Claude Code (Claude Sonnet 4.5)
# Date: 2026-02-03

set -e

# Configuration
RELEASE_NAME="todo-chatbot"
NAMESPACE="default"

# Parse arguments
if [ $# -ne 2 ]; then
    echo "Usage: $0 <component> <replicas>"
    echo "  component: backend or frontend"
    echo "  replicas: number of replicas (1-10)"
    exit 1
fi

COMPONENT=$1
REPLICAS=$2

# Validate component
if [ "$COMPONENT" != "backend" ] && [ "$COMPONENT" != "frontend" ]; then
    echo "ERROR: Component must be 'backend' or 'frontend'"
    exit 1
fi

# Validate replicas
if [ $REPLICAS -lt 1 ] || [ $REPLICAS -gt 10 ]; then
    echo "ERROR: Replicas must be between 1 and 10"
    exit 1
fi

echo "=== Scaling $COMPONENT to $REPLICAS replicas ==="
echo ""

# Get current replica count
CURRENT_REPLICAS=$(kubectl get deployment todo-chatbot-$COMPONENT -n $NAMESPACE -o jsonpath='{.spec.replicas}')
echo "Current replicas: $CURRENT_REPLICAS"
echo "Target replicas: $REPLICAS"
echo ""

# Scale deployment
echo "Scaling deployment..."
kubectl scale deployment/todo-chatbot-$COMPONENT --replicas=$REPLICAS --namespace=$NAMESPACE

# Wait for rollout
echo "Waiting for rollout to complete..."
kubectl rollout status deployment/todo-chatbot-$COMPONENT --namespace=$NAMESPACE

# Verify scaled state
echo ""
echo "Verifying scaled state..."
kubectl get pods -l app=todo-chatbot,component=$COMPONENT -n $NAMESPACE

# Log scale event
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
cat >> deployment/docs/deployment-log.md <<EOF

## Scale Event: $TIMESTAMP

**Component**: $COMPONENT
**Action**: Scale
**Previous Replicas**: $CURRENT_REPLICAS
**Current Replicas**: $REPLICAS
**Status**: Success
**Commit**: $(git rev-parse --short HEAD)

EOF

echo ""
echo "=== Scaling Complete ==="
echo "$COMPONENT scaled from $CURRENT_REPLICAS to $REPLICAS replicas"
